### ISSUE TITLE
Add support for Mac OS X

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#10]
- [x] Adapt SConstruct for MacOS
- [x] Adapt 3rdparty building for MacOS (#88)
- [x] Don't use version script on MacOS or maybe don't use it at all (#89)
- [x] Disable _POSIX_C_SOURCE on MacOS (doesn't work as expected)
- [x] Remove core::SpinMutex (we don't really need it) (#91)
- [x] Add target_posixtime and target_darwin to SConstruct (#99)
- [x] Port time functions to MacOS (#99)
- [x] Add Travis build for MacOS
- [x] Update wiki

**Comment by gavv** [comment]
### Portability issues

- [ ] Remove core::SpinMutex.
- [ ] Remove _POSIX_C_SOURCE.
- [ ] Add target_posixrt and target_darwin to SConstruct.
- [ ] Remove core::sleep_until_ms.
- [ ] Remove audio::TimedWriter.
- [ ] Replace core::Timer with core::Ticker with sleep_until_next_tick() method. We need two implementations: target_posixrt and tartget_darwin.
- [ ] Use core::Ticker instead of audio::TimedWriter in roc_pipeline.

**Comment by gavv** [comment]
OSX builds started failing:

https://travis-ci.org/roc-project/roc/builds/285192784

**Comment by gavv** [comment]
Fixed with 7a440febf3c3a41035a1cf34c96ca4a431dea992.
