### ISSUE TITLE
Rework audio encoder and decoder interfaces

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#211]
We need several enhancements in encoder/decoder interfaces:

- [x] make encoder and decoder protocol-independent and move from roc_rtp to roc_audio
- [x] make encoder and decoder operation on the buffer layer instead of the packet layer
- [x] make encoder and decoder stateful and make them track current position inside the packet and the position of the current packet in the whole stream
- [x] packetizer should be able to finish packet encoding earlier than expected — for #187
- [x] depacketizer should be able to retrieve current stream position from decoder — for #212
- [x] depacketizer should be able to provide the decoder with the next packet to decode a lost packet — for #51
