### ISSUE TITLE
Refactor packets for FECFRAME support

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#57]
For #48, we need some refactoring for our `IPacket` hierarchy.
### Packet interfaces

We now have to support the following interfaces for data contained in packet:
- **Routing and ordering**
  
  For any two packets, we should be able to say if they belong to the same session and how are they ordered. We use this when server routes and reorders received packets.
  
  Comes from RTP header or FECFRAME header.
- **RTP identification**
  
  This included Source ID, sequence number, timestamp. We use it in `Splitter`, `Watchdog`, `fec::Decoder`, and maybe somewhere else.
  
  Comes from RTP header.
- **FECFRAME identification**
  
  Block number and size, number of packet in block. We use it in `fec::Encoder` and `fec::Decoder`.
  
  Comes from FECFRAME header or footer.
- **Audio**
  
  Channel mask and samples. We use it only in `Streamer`. With opus support (#51), audio sample decoder will become stateful.
  
  Comes from RTP header and payload.
### Packet formats

Meanwhile, we have to support the following packet formats:
1. **Bare RTP audio packet**
   
   ```
   +---------------+
   |   RTP Header  |
   +---------------+
   | Audio payload |
   +---------------+
   ```
2. **FECFRAME source packet**
   
   ```
   +---------------+
   |   RTP Header  |
   +---------------+
   | Audio payload |
   +---------------+
   |   FEC footer  |
   +---------------+
   ```
   
   _(note that we can't parse RTP before parsing FEC footer, because RTP header contains no length field and FEC footer doesn't belong to RTP packet)_
3. **FECFRAME repair packet (non-RTP)**
   
   ```
   +---------------+
   |   FEC header  |
   +---------------+
   |  FEC symbols  |
   +---------------+
   ```
4. **FECFRAME repair packet (over RTP)**
   
   ```
   +---------------+
   |   RTP header  |
   +---------------+
   |   FEC header  |
   +---------------+
   |  FEC symbols  |
   +---------------+
   ```

Note that we may want to support multiple (distinct) formats for:
- audio payload (currently only PCM);
- FEC header, footer, and symbols (currently only LDPC).
### Packet flows

Examples of packet flows in server:
- **LDPC Source packet with RTP inside**
  - Parse LDPC footer and determine boundaries for RTP packet inside
  - Parse RTP packet header
  - Use RTP header for packet routing and ordering
  - Check RTP-specific fields (seqnum, timestamp) in `Watchdog`
  - Use LDPC fields in `fec::Decoder`
  - Extract audio from RTP payload in `Streamer`
- **LDPC Repair packet over RTP**
  - Parse RTP header
  - Parse LDPC header from RTP payload
  - Use RTP header for packet routing and ordering
  - Check RTP-specific fields (seqnum, timestamp) in `Watchdog`
  - Use LDPC fields in `fec::Decoder`
- **LDPC Repair packet over UDP**
  - Parse LDPC header
  - Use LDPC header for packet routing and ordering
  - Use LDPC fields in `fec::Decoder`

**Comment by gavv** [comment]
### Current design

```
                  +--------------+    +------------------+
                  | IAudioPacket |<---| rtp::AudioPacket |
                  +--------------+    +------------------+
 +---------+         /
 | IPacket | <------| 
 +---------+         \
                  +--------------+    +------------------+
                  |  IFECPacket  |<---|  rtp::FECPacket  |
                  +--------------+    +------------------+
```

**Comment by gavv** [comment]
### TODO

#### Interfaces

Replace inheritance with aggregation:

- [ ] Move ordering and rtp identification from `IPacket` to `packet.order()` and `packet.pos()`
- [ ] Move `IFECPacket` to `packet.fec()`
- [ ] Move `IAudioPacket` to `packet.audio()`
- [ ] Add packet flags

#### RTP

- [ ] Merge `rtp::RTP_Packet`, `rtp::AudioPacket`, and `rtp::FECPacket` into single `rtp::Packet`
- [ ] Make packet parser and composer stateful
- [ ] Introduce `RTPMap` and register supported audio formats there; use its instance in parser and composer (we'll also use it to register encapsulated packet formats)
- [ ] Add support for packets encapsulated in RTP (we'll used for LDPC repair packets inside RTP)

#### Server

- [ ] Use packet ordering and flags for routing in `roc_pipeline`, `PacketQueue`, and `PacketRouter`
- [ ] Use `packet.pos()` only in `Watchdog` and `fec::Decoder`
- [ ] Use `packet.fec()` only in `fec::Decoder`
- [ ] Use `packet.audio()` only in `Streamer`

#### Client

- [ ] Update `Splitter`
- [ ] Update `fec::Encoder`

**Comment by gavv** [comment]
Done.
